### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Moyan-lll** [dbader/alfred-countdown-timer#15]
hello,when i run the timer.py it tells me that:"no module named ojbc"
i check every file but can't find the module,it's kind of you if you tell me what's matter with me.thank you

**Comment by theyongdai** [comment]
I think the objc module is part of [Alfred](https://www.alfredapp.com/). Are you running the project as a [Alfred](https://www.alfredapp.com/) plugin?

**Comment by Moyan-lll** [comment]
> I think the objc module is part of [Alfred](https://www.alfredapp.com/). Are you running the project as a [Alfred](https://www.alfredapp.com/) plugin?

thanks for your reply,i am a beginner and i just download the project code and run on my pycharm.i thought what i download is all need.so what should i do next,thanks again.

**Comment by theyongdai** [comment]
I suppose, try to run the project as an [Alfred](https://www.alfredapp.com/) plugin.
