### ISSUE TITLE
Is there a way to change the alarm sound?

### ISSUE THREAD

**Issue by AlexanderKvamme** [dbader/alfred-countdown-timer#16]
Is the .mp4 file bundled anywhere where i can change it? Not very familiar with alfred extensions but id be happy to share my results if anyone can point me in the right direction!

The reason for wanting this is that the sound is too dominant for me to use it at work as i want, but the timer has been really helpful so i would like to make it work :)

**Comment by stanislavshabalin** [comment]
Hey, Alexander! @AlexanderKvamme 

1. Open up the workflow in Alfred Preferences, double click on any node (first one, for example)
2. Click the small "stove" icon near the Cancel button

It will open up a finder window with files, bundled with the workflow. You should be able to swap the file for another with the same name (or edit the python script to use another file name).

Please let me know if this works :-) I've used Alfred 3 for the screenshot, but hopefully it's similar in version 4.
<img width="710" alt="Screen Shot 2019-11-12 at 22 58 59" src="https://user-images.githubusercontent.com/420771/68706269-87d4d500-05a0-11ea-9038-c2d324c3d796.png">

**Comment by AlexanderKvamme** [comment]
Thank you so much for your explaination @stanislavshabalin! It works perfectly :)
